server:
  port: 8500  #启动端口
spring:
  application:
    name: shenheyuan-service   #服务名
  cloud:
    nacos:
      discovery:
        server-addr: 120.25.164.209:8848   #nacos注册中心地址
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/admin?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: cn.edu.glmc.bean
